### ISSUE TITLE
Add KeyPath to the PathFilter class

### ISSUE THREAD

**Issue by linojon** [mmattner/vPinBackupManager#16]
I suggest we expand the PathFilter class to allow optional value for a KeyPath that will say how we query into the file. The value is roughly based on XPath syntax but can be adopted for various file types that contains data for multiple tables.

**CSV files**
Comma delimited files have one row for each table. 
KeyPath in the format "/COLUMN/VALUE" where COLUMN can be a number (n'th column) or a name (for CSV files with a first header row). VALUE is a tokenized string.

Examples
* VPinMAME\VPMAlias.txt: the KeyPath will be "/0/[GAMECODE]" meaning first column with value of GAMECODE.
* Pinball-Y has a GameStats.csv file. The KeyPath might be "/Game/[GAMENAME].[EMULATOR]" where "Game" is the column name, and the value uses Pinball-Y's table display name (GAMENAME) and emulator name [EMULATOR]. This is just a potential example.

**INI files**
INI files are used to store table-specific settings in their own section. Probably always at the root since INI files are not structured. Keypath specifies the name of the INI section.

Examples:
* VisualPinball\DmdDevice.ini: KeyPath: "/[GAMECODE]" (i'm not sure if this is always what we get for GAMECODE or it might be a different string on some tables?)
* 

**XML files**
XML files are used to store table-specific settings in their own table-specific tag sections, which may not necessarily be at the root. The KeyPath acts similar to an XPath expression.

Examples:
* VisualPinball\Tables\B2STableSettings.xml: KeyPath: "/B2STableSettings/{ROM}"
* PinballY\Databases\[EMULATOR]\[EMULATOR].xml: "/menu/game[@name="{GAMENAME}"]"

**Comment by mmattner** [comment]
Would this effectively allow uses to configure their own searches for game specific content in table scritps or is it more targetted at pulling content out of files such as ini / xml files ?

Ultimately if there is a use case to add this - particularly if it makes these new files to backup an easier process Im supportive. I think it can probably be made optional ... ie if we parse config without it it doesnt break (I already do this for fitlers in general) so it should be fine .. and I can help if needed.

**Comment by mmattner** [comment]
@linojon  Just a thought - does this effectively provide the same sort of functionality as 'filter' allocated to a PathFilter.

Ie - for the 'VPREG' Path filter we have:
# PathFilter(@"User\VPReg.stg", new List<string> { Constants.TOKEN_GAMEVPREGCODE }, "VPReg file entry", false, FILTER_PATH_TYPE.VPREG)

So this means:
Path =  User\VPReg.stg                       _(which is actually a file, rather than a path)_
Filters (list with one entry) = "[GAMEVPREGCODE]"            _(which is the actual equivalent of keypath into the VPReg file)_


So in your cases:
Path = Tables\B2STableSettings.xml
Filters = [ {"/B2STableSettings/[GAMECODE]" }]

and 

Path = VisualPinball\DmdDevice.ini
Filters = [ {"[GAMECODE]" }]

would work, assuming that we have to specific special filter types for these, maybe generic types like XML_ENTRY INI_ENTRY or something to be generic. 
Ie this means if you had a path filter that was an INI_ENTRY then the Path value represents the full path including the filename of the ini file to extract content from, and the filter represents the PathFilter concept.

This has the benefit of removing the need to have a Path Filter with a Path and an optional Filter or KeyPath entry within it, so keeps our UI simpler to use.

**Comment by mmattner** [comment]
Have moved this to in progress and experct we will be able to close based on above analysis and demopnstration of this working for CSV files in https://github.com/mmattner/vPinBackupManager/issues/17

**Comment by linojon** [comment]
This sounds like a very good solution
