### ISSUE TITLE
Support for VPMAlias.txt

### ISSUE THREAD

**Issue by linojon** [mmattner/vPinBackupManager#17]
The VisualPinball\VPinMAME\VPMAlias.txt file is a common way to let different VPX games use the same rom. By adding an alias to the file, and then changing the cGameName in the table script, VPX thinks you're using one rom name but its actually using another. All over assets based on the rom name use the aliased one.

The file is actually like a CSV file, with 2 columns. The first is the new name, the second is the actual rom file name (without extension). .e.g.

```
blaze,csmic_l1
FF,gw_l5
sttng_l7_pup,sttng_l7
```

**backup**
When backing up we should extract the row for the games GAMECODE and save that.
And also back up the original rom file (.zip)

**delete**
Delete should remove the alias from the file.
Can also remove the rom file if no other game is using it.

**restore**
Appends the alias row to the file.
Adds the rom file.

**implementation**
* I recommend we use a CSV package and implement a CSVUtilities over it so we have a reusable solution for other CSV files (e.g. Pinball-Y uses CSV as its media database).
* Add a CSV FILTER_PATH_TYPE
* Expand the PathFilter class to allow optional value for a KeyPath that will say how we query into the file. For VPMAlias.txt thie KeyPath will be "/0/[GAMECODE]" meaning first column with value of GAMECODE.

**Comment by mmattner** [comment]
Agreed

**Comment by mmattner** [comment]
https://github.com/mmattner/vPinBackupManager/tree/Issue17-SupportForVPMAlias.txt exiswts with initial changes to add a CSV utilities package alowing rows to be extracted based on a search value in supplied column.
Other commands can be added as needed.

**Comment by mmattner** [comment]
Thinking about this today, one thing to note is the VPMAlias entries  map cGameName values in tables to real roms. This means that without thought the GAMECODE value extracted from games will not match to ROMS for games with aliases. To address this, we need to determine if a game has an alias prior to locating manfest entries and also search for that. Maybe we add a ALIASED_GAMECODE variable (i could be ALIASED_ROM, but using this name is consistent within the tool).

Then add a filter of the ROM folder for the aliased value if it exists.

**Comment by mmattner** [comment]
Furtther context to how VPM Alias works:

- VPM alaises only apply to games that use ROMS,.
- Normally games with ROMs have the value of cGameName set to the name of the ROM
- VPM aliases are used when multiple games use the same ROM, but you want to use different associated files (ie Pup Packs, altsound/altcolor/NVRAM etc)
- To achieve this, users modify the gamescript and set the value of cGameName to a different value (ie "NEWNAME") for all but one of the games using the ROM ("OLDNAME") and add an entry in VPMAliases.txt  like "NEWNAME,OLDNAME"
- When the game starts, vPinMame loads the ROM caled "OLDNAME" but then loads altsound, altcolor, nvram, puppacks etc matching "NEWNAME"

So the code does the following:
Once all variables haver been extracted we need to find out if there is an alias set up for it. The normal approach is to just check for a value matching cGameName, but because we have overrides (just in case we couldnt correctly extract cGameName) we first check if there is an override for gameName. 
If there is we uwe the override to look for an alaisd entry, otherwise we take the extracted value of cGameName or any ROM value passed in.

So we are baiscally saying "look for a VPMAlias entry matching the value of GAMCODE that we will be using elsewhere in the code, which will either be the value we manually override with, or the value extracted (if there was no override)"

To test:
- get two games that use same rom, ie get two versions of attach from mars
- ensure you have the AFM rom (afm_113b.zip) sitting in roms and add some altcolor//altsound/nvrom/pup pack files/folders to match (even if you just create dummies)
- in one version, edit the script and change the value of cGameName to "testrom"
- start VPBM and note the files matched for both versions of AFM and notethat the verison with original cGameName matches on the ROM, plus on the altsound/altcolor etc but the version with new value of cGameName does not match on rom or any of these folders
- now add the entry "testrom,afm_113b" to the VPMALias.txt file and refresh/restart VPBM
- note that now the game with updated cGameName matches on the ROM but not on the other files/folders
- add some altcolor//altsound/nvrom/pup pack files/folders with names to match "testrom" and restart/refresh VPBM
- note that now these other entries show up in the tool as matches
- now go into the script and change the value of cGameName to "test" + "rom" (or some form of code that we cant parse)
- restart/refresh VPBM and note that we no longer find all the matches for the "Testrom" files/foldersd, or to the aliased ROM
- go into VPBM custom filters panel and click the override checkbox for ALIASEDGAMENAME and set its value to "testrom" and click the Update button. Yuo should immediately see the files now appear as the override is now used to search the VPMAliase.txt file
