### ISSUE TITLE
Support for EM files

### ISSUE THREAD

**Issue by mmattner** [mmattner/vPinBackupManager#21]
Some games use EM files for high score storagew (potentially other information, but I havent been made aware of that).
EM files are simple text files in the usere directory containing the stored content.

Process for backup/delete/rstore hasn't yet been determined, information from Syd is that the only challenge with them is finding their name, this is in the table script - but sonds like its normally (or always) based on the tablename value.
Three games known to use EM files are:

1. Hayburners
2. Aces High
3. Baseball 

So the easiest approach is to probably install these games, run them and see what is produced.

**Comment by linojon** [comment]
We want to back up table-specific data, including high scores, in User\*.txt files. (Otherwise ROM-less games use the Windows Registry for this). The question is discovering if a table uses this file and what is its base file name. From a sample of games here are relevant lines of code we could use:

* Hayburners
`Const HSFileName="Hayburners_51VPX.txt"`
`Set ScoreFile=FileObj.CreateTextFile(UserDirectory & HSFileName,True)`
	
* Aces High
`Set ScoreFile=FileObj.CreateTextFile(UserDirectory & "Aces_High.txt",True)`
`Set ScoreFile=FileObj.GetFile(UserDirectory & "Aces_High.txt")`

* Baseball
`Const HSFileName="Baseball_70VPX.txt"`
`Set ScoreFile=FileObj.CreateTextFile(UserDirectory & HSFileName,True)`
`Set ScoreFile=FileObj.GetFile(UserDirectory & HSFileName)`

* Big Indian
`Const TableName = "big-indian" ' file name to save highscores and other variables`
`Set ScoreFile = FileObj.GetFile(UserDirectory & TableName& ".txt")`

* America’s Most Haunted
`Const LMEMTableConfig="LMEMDOFTables.txt"`
`Set LMConfig=FileObj.CreateTextFile(UserDirectory & LMEMTableConfig,True)`

So it seems that in the vbs script we can look for some combination of lines that reference UserDirectory and the substring ".txt". Maybe something like this

1. if the line contains "UserDirectory &" ,then suppose that the filename is in the match that comes after
2. if the match is a literal string (in quotes) that is the filename
3. else if the match is a variable + "& ".txt" look up the variable and construct the filename
4. else if the match is a variable, look up the variable and that is the filename
5. If the filename contains ".txt" then we found it
6. else not successful

**Comment by mmattner** [comment]
Because of the vagaries of how tables code this stuff up, we will also need to strongly consider adding the name as a variable seen in the custom filters panel on the GUI. We are almost at the point where these variables should be pulled off of there and displayed in their own right.... but lets do that as a seperate exercise - as I have some further thoughts on this


Your logic seems ok, I think its also clear that there will be a CreateTextFile call in the script. I wonder if we can deduce anything further from where this is used. Ie can we find a call somewhere that is clearly about writing high scores that uses this variable. If so, we will 100% know that the game uses EM highscores (if we dont already, and if we do know already, then thats awesome and ignore what I said)
